services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: parking-api
    ports:
      - "${API_PUBLISHED_PORT:-8000}:${API_PORT:-8000}"
    environment:
      - APP_HOST=${API_HOST:-0.0.0.0}
      - APP_PORT=${API_PORT:-8000}
      - APP_LOG_LEVEL=${API_LOG_LEVEL:-INFO}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${APP_PORT:-8000}/api/v1/health || exit 0"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: parking-streamlit
    ports:
      - "${STREAMLIT_PUBLISHED_PORT:-80}:${STREAMLIT_PORT:-8501}"
    environment:
      - APP_HOST=${API_SERVICE_NAME:-api}
      - APP_PORT=${API_PORT:-8000}
      - APP_API_URL=http://${API_SERVICE_NAME:-api}:${API_PORT:-8000}
      - STREAMLIT_PORT=${STREAMLIT_PORT:-8501}
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${STREAMLIT_PORT:-8501} || exit 0"] 
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped