services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: parking-api
    ports:
      - "8000:8000"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/api/v1/health || exit 0"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: parking-streamlit
    ports:
      - "8501:8501"
    environment:
      - APP_HOST=api
      - APP_PORT=8000
      - APP_API_URL=http://api:8000
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501 || exit 0"] 
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped